export const generateCategoryListStyles = (colors) => ({
    container: { flex: 1 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
    errorText: { color: colors.errorRed, textAlign: 'center', marginTop: 20 },
    emptyText: { color: colors.textGrey, textAlign: 'center', marginTop: 20, fontSize: 16 },
    listContainer: { paddingBottom: 20 },
    filterToggleBtn: { backgroundColor: colors.cardBackground, padding: 12, borderRadius: 8, alignItems: 'center', marginBottom: 15, borderWidth: 1, borderColor: colors.borderColor },
    filterToggleText: { fontWeight: 'bold', color: colors.textMain },
    filterPanel: { backgroundColor: colors.cardBackground, padding: 15, borderRadius: 12, marginBottom: 15, elevation: 2, borderWidth: 1, borderColor: colors.borderColor },
    input: { borderWidth: 1, borderColor: colors.borderColor, borderRadius: 8, padding: 10, marginBottom: 10, backgroundColor: colors.background, color: colors.textMain },
    row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
    halfInput: { width: '48%', marginBottom: 0 },
    divider: { height: 1, backgroundColor: colors.borderColor, marginVertical: 15 },
    sortBtn: { width: '48%', padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.primaryAccent, alignItems: 'center' },
    activeSort: { backgroundColor: colors.primaryAccent },
    sortText: { color: colors.primaryAccent, fontWeight: '600', fontSize: 12 },
    activeSortText: { color: '#fff' },
    filterSection: { marginBottom: 15 },
    filterLabel: { fontSize: 14, fontWeight: 'bold', color: colors.textMain, marginBottom: 8 },
    chipScroll: { flexDirection: 'row' },
    chip: { paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.borderColor, marginRight: 8 },
    activeChip: { backgroundColor: colors.primaryAccent, borderColor: colors.primaryAccent },
    chipText: { fontSize: 13, color: colors.textMain },
    activeChipText: { color: '#fff', fontWeight: 'bold' },
    clearBtn: { backgroundColor: colors.errorRed, padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 15 },
    clearBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
    card: { flexDirection: 'row', backgroundColor: colors.cardBackground, padding: 15, borderRadius: 12, marginBottom: 15, elevation: 2, borderWidth: 1, borderColor: colors.borderColor },
    image: { width: 80, height: 80, marginRight: 15 },
    details: { flex: 1, justifyContent: 'center' },
    name: { fontSize: 15, fontWeight: '600', color: colors.textMain, marginBottom: 5 },
    price: { fontSize: 16, color: colors.primaryAccent, fontWeight: 'bold', marginBottom: 10 },
    addBtn: { backgroundColor: colors.primaryAccent, paddingVertical: 8, borderRadius: 6, alignItems: 'center' },
    addBtnText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 12 }
});