export const generateProductDetailStyles = (colors, isLandscape) => ({
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    errorText: { color: colors.errorRed, textAlign: 'center', marginTop: 50, fontSize: 18 },
    container: { flex: 1, backgroundColor: colors.background },
    fixedHeader: { backgroundColor: colors.background, paddingHorizontal: 20, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.borderColor },
    backBtn: { marginTop: 30, paddingVertical: 10, paddingHorizontal: 16, backgroundColor: colors.cardBackground, borderRadius: 8, alignSelf: 'flex-start', borderWidth: 1, borderColor: colors.borderColor },
    backBtnText: { fontSize: 15, fontWeight: '600', color: colors.textMain },
    scrollContent: { padding: 20, paddingBottom: 40 },
    layoutWrapper: { flexDirection: isLandscape ? 'row' : 'column', gap: 20 },
    imageColumn: { flex: isLandscape ? 1 : undefined },
    specsColumn: { flex: isLandscape ? 1 : undefined },
    image: { width: '100%', height: 250, backgroundColor: colors.cardBackground, borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: colors.borderColor },
    titleContainer: { backgroundColor: colors.cardBackground, padding: 20, borderRadius: 12, marginBottom: isLandscape ? 0 : 20, borderWidth: 1, borderColor: colors.borderColor },
    brand: { fontSize: 14, color: colors.textGrey, textTransform: 'uppercase', fontWeight: 'bold', marginBottom: 4 },
    name: { fontSize: 22, fontWeight: 'bold', color: colors.textMain, marginBottom: 10 },
    price: { fontSize: 26, color: colors.primaryAccent, fontWeight: 'bold', marginBottom: 10 },
    stockStatus: { fontSize: 16, fontWeight: '600' },
    specsCard: { backgroundColor: colors.cardBackground, padding: 20, borderRadius: 12, borderWidth: 1, borderColor: colors.borderColor },
    specsHeader: { fontSize: 20, fontWeight: 'bold', color: colors.textMain, marginBottom: 15 },
    divider: { height: 1, backgroundColor: colors.borderColor, marginBottom: 15 },
    specRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.borderColor },
    specLabel: { fontSize: 16, color: colors.textGrey, flex: 1 },
    specValue: { fontSize: 16, fontWeight: '500', color: colors.textMain, flex: 1, textAlign: 'right' }
});