export const generateProfileStyles = (colors) => ({
    mainContainer: { flex: 1 },
    scrollContent: { padding: 20, paddingBottom: 40 },
    landscapeRow: { flexDirection: 'row', gap: 30 },
    landscapeCol: { flex: 1 },
    
    segmentContainer: { flexDirection: 'row', margin: 20, marginBottom: 0, backgroundColor: colors.cardBackground, borderRadius: 12, padding: 4, borderWidth: 1, borderColor: colors.borderColor },
    segmentBtn: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 8 },
    segmentBtnActive: { backgroundColor: colors.background, shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },
    segmentText: { color: colors.textGrey, fontWeight: '600' },
    segmentTextActive: { color: colors.textMain },
    
    sectionContainer: { marginBottom: 20 },
    sectionHeader: { fontSize: 22, fontWeight: 'bold', color: colors.textMain, marginBottom: 20, marginTop: 10 },
    inputContainer: { marginBottom: 15 },
    label: { fontSize: 13, fontWeight: '600', color: colors.textMain, marginBottom: 6 },
    inputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.borderColor, borderRadius: 10, paddingHorizontal: 15, height: 48 },
    input: { flex: 1, color: colors.textMain, fontSize: 15 },
    errorText: { color: colors.errorRed, fontSize: 12, marginTop: 4 },
    statusMsg: { textAlign: 'center', fontSize: 14, fontWeight: 'bold', marginVertical: 10 },
    saveBtn: { backgroundColor: colors.primaryAccent, paddingVertical: 15, borderRadius: 10, alignItems: 'center', marginTop: 10 },
    saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
    
    buildCard: { backgroundColor: colors.cardBackground, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: colors.borderColor, overflow: 'hidden' },
    buildCardHeader: { padding: 15, borderBottomWidth: 1, borderBottomColor: colors.borderColor },
    buildTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    buildTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textMain, flex: 1 },
    renameContainer: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    renameInput: { flex: 1, backgroundColor: colors.background, color: colors.textMain, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 6, borderWidth: 1, borderColor: colors.borderColor },
    actionIcon: { padding: 4 },
    buildContent: { padding: 15 },
    buildDate: { fontSize: 13, color: colors.textGrey, marginBottom: 4 },
    buildId: { fontSize: 13, color: colors.primaryAccent, fontWeight: 'bold', marginBottom: 15 },
    partsList: { backgroundColor: colors.background, borderRadius: 8, padding: 12, marginBottom: 15 },
    partRow: { flexDirection: 'row', marginBottom: 6 },
    partLabel: { width: 90, fontSize: 13, fontWeight: '600', color: colors.textGrey },
    partValue: { flex: 1, fontSize: 13, color: colors.textMain, fontWeight: '500' },
    buildActions: { flexDirection: 'row', gap: 10 },
    buildBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.borderColor },
    buildBtnText: { fontSize: 14, fontWeight: '600', color: '#FFF' },
    emptyText: { color: colors.textGrey, textAlign: 'center', marginTop: 20, fontStyle: 'italic' },
    
    guestContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 30, backgroundColor: colors.background },
    guestTitle: { fontSize: 24, fontWeight: 'bold', color: colors.textMain, marginBottom: 10 },
    guestSubtitle: { fontSize: 16, color: colors.textGrey, textAlign: 'center', marginBottom: 30, lineHeight: 22 },
    loginBtn: { backgroundColor: colors.primaryAccent, paddingVertical: 15, paddingHorizontal: 30, borderRadius: 12, width: '100%', alignItems: 'center' },
    loginBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' }
});